<<<<<<< HEAD
CREATE TABLE users (id VARCHAR(255)PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(20) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
  role VARCHAR(10) DEFAULT 'user' NOT NULL )

  DROP TABLE users
  SELECT * FROM users
=======
CREATE TABLE users (id VARCHAR(255)PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
  role VARCHAR(255) DEFAULT 'user' NOT NULL );
>>>>>>> adbbaf2908af5ff9cbc853a6f35ed5ece0462ab8
