CREATE TABLE users (id VARCHAR(255)PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(20) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
  role VARCHAR(10) DEFAULT 'user' NOT NULL )

  DROP TABLE users
  SELECT * FROM users