
##register user
POST http://localhost:3002/auth/register
Content-Type: application/json


{
    "name":"cena Doe",
    "email":"cena112@gmail.com",
    "password":"123"
}

###login user
POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "email":"john112@gmail.com",
    "password":"123"
}

