POST http://localhost:3002/auth/register
Content-Type: application/json


{
    "name":"Melissa Doe",
    "email":"mel112@gmail.com",
    "password":"123"
}

#####
GET http://localhost:3002/auth/login
Content-Type: application/json

{
    "email":"mel@gmail.com",
    "password":"123"
}