

GET http://localhost:5203/projects/all
Content-Type: application/json

### Create a project
POST http://localhost:5203/projects/create
Content-Type: application/json


{

  "name": "Sample Project",
  "description": "This is a sample project.",
  "end_date": "2024-06-30",
  "user_id": "85108478-b981-4c80-a0e9-621f8804904e"
  
}