GET http://localhost:3002/projects/all
Content-Type: application/json

### Create a project
POST http://localhost:3002/projects/create
Content-Type: application/json

{
  
    "name": "Project Gamma",
    "description": "Description for Project Gamma",
    "end_date": "2024-11-30",
    "user_id": "user002",
    "user_email":"bob@example.com"
}


